# Checklist: 

1. Set up an AWS account 
2. To use this notebook tutorial, install python 2.7, boto3, and jupyter notebook 

P.S. use `jupyter nbconvert --to html Uploader\ and\ Downloader.ipynb` to generate HTML from this notebook for better viewing experience

In [4]:
#!/usr/bin/python
import sys
print(sys.version)

2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 16:24:02)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

In [9]:
import a_uploadHIT as a
reload(a)
client = a.make_conn(sandbox = True) # sandbox connection
client = a.make_conn(sandbox = False) # public connection

# response = client.delete_hit(
#     HITId='30ZKOOGW2W4DZGJLVOMGTA8UGZJA1Z' 
# This operation can be called with a status of: Reviewing, Reviewable (1559614483467)
# )

Using sandbox
Press enter to confirm connection to PUBLIC

# Step 1: Upload an HTML-based HIT to Amazon Mechanical Thurk (AMT)

* __Step 1__: Upload the html files to s3 -- `a.upload_html_to_s3()`
* __Step 2__: Create the HIT assignment using the html -- `a.publish_url_as_HIT()`
* __Step 3__: Test to see if the HIT works
    * go to https://workersandbox.mturk.com
    * search for the title of your HITs (it may take a few minutes to show up.)
    * try it out

P.S. Here are some resources on the configuration your HIT:
* Qualification in boto3:   https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/mturk.html
* Qualification Type IDs:   https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI-legacy/ApiReference_QualificationRequirementDataStructureArticle.html#ApiReference_QualificationType-IDs
* best practice:   https://blog.mturk.com/qualifications-and-worker-task-quality-best-practices-886f1f4e03fc

In [116]:
url = a.upload_html_to_s3(html_filepath ='HIT_give_instructions.html', 
                   s3_bucket_name = 'nusrls', # Change this to the name of the bucket you created.
                   keyname = 'HIT_give_instructions.html')

print url
a.publish_url_as_HIT([url], 
                    HIT_group_title = 'Give instructions',
                    HIT_group_description = 'Give instructions based on pairs of images',
                    sandbox = True, # Uploading to sandbox or not. Use sandbox for debugging.
                    numAssignmentsPerHIT = 200, # How many unique workers for each URL 
                    durationSecPerHIT = 1200, # How long each assignment will be
                    completionRewardUSD = 0.5, # How much you will pay them upon completion.)
                    )

https://s3.amazonaws.com/nusrls/HIT_give_instructions.html
Press enter to confirm connection to PUBLIC

('\nBalance remaining: ', {u'AvailableBalance': u'542.51', 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '6fc1b0bb-3f87-43cc-92a8-0ce64e8b7e77', 'HTTPHeaders': {'x-amzn-requestid': '6fc1b0bb-3f87-43cc-92a8-0ce64e8b7e77', 'date': 'Tue, 04 Jun 2019 02:11:58 GMT', 'content-length': '29', 'content-type': 'application/x-amz-json-1.1'}}}, '\n')
Created HIT 30ZKOOGW2W4DZGJLVOMGTA8UGZJA1Z at https://s3.amazonaws.com/nusrls/HIT_give_instructions.html

defaultdict(list,
            {'HITFrameHeight': [768],
             'HITId': [u'30ZKOOGW2W4DZGJLVOMGTA8UGZJA1Z'],
             'QualificationRequirements': [{'Comparator': 'GreaterThanOrEqualTo',
               'IntegerValues': [96],
               'QualificationTypeId': '000000000000000000L0',
               'RequiredToPreview': True}],
             'assignmentDurationInSeconds': [1200],
             'autoApprovalDelayInSeconds': [86400],
             'completionRewardUSD': [0.5],
             'lifetimeInSeconds': [1209600],
             'numAssignments': [200],
             'sandbox': [False],
             'title': ['Give instructions'],
             'url': ['https://s3.amazonaws.com/nusrls/HIT_give_instructions.html']})

In [183]:
url = a.upload_html_to_s3(html_filepath ='HIT_set_table.html', 
                   s3_bucket_name = 'nusrls', # Change this to the name of the bucket you created.
                   keyname = 'HIT_set_table.html')

print url
a.publish_url_as_HIT([url], 
                    HIT_group_title = 'Drag and Rotate',
                    HIT_group_description = 'Drag and rotate objects according to instructions',
                    sandbox = False, # Uploading to sandbox or not. Use sandbox for debugging.
                    numAssignmentsPerHIT = 1000, # How many unique workers for each URL 
                    durationSecPerHIT = 1200, # How long each assignment will be
                    completionRewardUSD = 0.2,) # How much you will pay them upon completion.)

https://s3.amazonaws.com/nusrls/HIT_set_table.html
Press enter to confirm connection to PUBLIC

('\nBalance remaining: ', {u'AvailableBalance': u'346.51', 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '11b5d2e0-a0f4-474d-8735-9412cd7b5a65', 'HTTPHeaders': {'x-amzn-requestid': '11b5d2e0-a0f4-474d-8735-9412cd7b5a65', 'date': 'Wed, 05 Jun 2019 17:30:07 GMT', 'content-length': '29', 'content-type': 'application/x-amz-json-1.1'}}}, '\n')
Created HIT 3VLL1PIENQMZWGYUDI0QMZCBJ0POZ1 at https://s3.amazonaws.com/nusrls/HIT_set_table.html

defaultdict(list,
            {'HITFrameHeight': [768],
             'HITId': [u'3VLL1PIENQMZWGYUDI0QMZCBJ0POZ1'],
             'QualificationRequirements': [{'Comparator': 'GreaterThanOrEqualTo',
               'IntegerValues': [96],
               'QualificationTypeId': '000000000000000000L0',
               'RequiredToPreview': True}],
             'assignmentDurationInSeconds': [1200],
             'autoApprovalDelayInSeconds': [86400],
             'completionRewardUSD': [0.2],
             'lifetimeInSeconds': [1209600],
             'numAssignments': [1000],
             'sandbox': [False],
             'title': ['Drag and Rotate'],
             'url': ['https://s3.amazonaws.com/nusrls/HIT_set_table.html']})

# Step 2: Download the data contributed by AMT workers

In [2]:
import b_downloadAssignments as b
reload(b)

assignmentData = b.download_assignments(sandbox = False)

# The workers' data are stored in the key 'answer'

In [1]:
print(assignmentData.keys())

from pprint import pprint
pprint(dict(assignmentData))
# allWorkers = []
# for a in assignmentData['workerId']: 
#     allWorkers.append(a)
# pd.DataFrame(allWorkers).to_csv('workerID.csv', encoding='utf-8', index=False)

# assignmentData.keys() 
# assignmentData['workerId']

# TASK 1 -------- for instructions

In [40]:
import json 
import numpy as np
import pandas as pd

IDs = {'3FBEFUUYRK3862KI1UYXO6ZBOY26A8':0, '30ZKOOGW2W4DZGJLVOMGTA8UGZJA1Z':0} # '3VW0145YLYALWY8EIGIR61ZG5Y4MJY':0, 
time_strs = ["05-28", "05-29", "05-30", "05-31", "06-01","06-02","06-03", "06-04", "06-05", "06-06", "06-07", "06-08","06-09","06-10","06-11","06-12","06-13","06-14"]

def extract_answer_data(answer_string): 
    to_return = ""
    middle = answer_string.split('<FreeText>')[1].split('</FreeText')[0]
    if len(middle) > 2:
        to_return = json.loads(middle) 
    return to_return

def find_between( s, first, last ):
    try:
        start = s.index( first ) + len( first )
        end = s.index( last, start )
        return s[start:end]
    except ValueError:
        return ""
    
def get_answer_on_date(allMyAnswers, hour_string):
    keyword = 'instruction'
    for i in range(len(assignmentData['answer'])):
        for ID, count in IDs.iteritems():
            if assignmentData['HITId'][i] == ID: # 3M93N4X8HKLOUTLJ2DEDIAYMWKPJS3':# 
                IDs[ID] = IDs[ID] + 1
                a = assignmentData['answer'][i]
                for time_string in time_strs:
                    if ("2019-" + time_string) in str(assignmentData['acceptTime'][i]):
                        hour = find_between(str(assignmentData['acceptTime'][i]), ' ',':')
                        if True: #int(hour) >= int(hour_string):
                            answerData = extract_answer_data(a)
                            if answerData.has_key(keyword):
                                answerData["HITId"] = assignmentData['HITId'][i]
                                answerData["acceptTime"] = str(assignmentData['acceptTime'][i]).replace('datetime.datetime(','').replace(', tzinfo=tzlocal())','')
#                                 print(answerData["acceptTime"])
                                allMyAnswers.append(answerData)
    for ID, count in IDs.iteritems():
        print(ID + ": " +str(IDs[ID]))
    
    return allMyAnswers

In [41]:
allMyAnswers = []
get_answer_on_date(allMyAnswers, "0")
# get_answer_on_date(allMyAnswers, "2019-05-27", "20")
# get_answer_on_date(allMyAnswers, "2019-02-09")
# get_answer_on_date(allMyAnswers, "2019-02-10")
# get_answer_on_date(allMyAnswers, "2019-02-12")
            
len(allMyAnswers)
# allMyAnswers

30ZKOOGW2W4DZGJLVOMGTA8UGZJA1Z: 200
3FBEFUUYRK3862KI1UYXO6ZBOY26A8: 419

619

In [164]:
import csv

start_index = 251
length = 0
count = 0

csvData = []

for i in range(len(allMyAnswers)):
    answer = allMyAnswers[i]
    j_answer = {}
    j_answer["video_name"] = answer["videoName"].encode("ascii")
    j_answer["HIT_Id"] = answer["HITId"].encode("ascii")
    j_answer["accept_time"] = answer["acceptTime"].encode("ascii")
    instructions = []
    
    infile_length = 0
    infile_count = 0
    for ins in answer["instruction"]:
        sentence = ins.encode("ascii").replace("&amp;nbsp; ", " ").replace("&lt;br&gt;","")
        length = length + sentence.count(" ") + 1
        count = count + 1
        infile_length = infile_length + sentence.count(" ") + 1
        infile_count = infile_count + 1
        instructions.append(sentence)
        
    j_answer["instructions"] = instructions
    
    ave_length = infile_length/infile_count
    name = 'data_'+str(start_index+i)+'.json'
    csvData.append([name, j_answer["video_name"], infile_count, ave_length])
    
    if infile_length/infile_count < 6:
        print(str(start_index+i))
        
    with open("instruction_data/"+ name, 'w') as outfile:  
        json.dump(j_answer, outfile, indent=4, sort_keys=False)

print("Average length: "+str(length/count))

with open('instruction_data/astats_'+str(len(allMyAnswers))+'.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows(csvData)

csvFile.close()

251
253
260
263
264
266
280
290
293
310
311
321
331
347
396
433
Average length: 10

# TASK 2 -------- for actions

Generate csv table of workers' actions. Each row is a step in the sequence, each column has the following format:
`object-1 | x-axis | y-axis | angle | object-2 | x-axis ...`

In [21]:
import json 
import numpy as np
import pandas as pd

IDs = {'3VLL1PIENQMZWGYUDI0QMZCBJ0POZ1':0} #'3M93N4X8HKLOUTLJ2DEDIAYMWKPJS3':0, 
time_strs = ["06-03", "06-04", "06-05", "06-06", "06-07", "06-08","06-09","06-10","06-11","06-12"]

def extract_answer_data(answer_string): 
    to_return = ""
    middle = answer_string.split('<FreeText>')[1].split('</FreeText')[0]
    if len(middle) > 2:
        to_return = json.loads(middle) 
    return to_return

def get_location_on_date(allMyAnswers):
    keyword = 'locations'
    for i in range(len(assignmentData['answer'])):
        for ID, count in IDs.iteritems():
            if assignmentData['HITId'][i] == ID: # 3M93N4X8HKLOUTLJ2DEDIAYMWKPJS3':# 
                IDs[ID] = IDs[ID] + 1
                a = assignmentData['answer'][i]
                for time_string in time_strs:
                    if ("2019-" + time_string) in str(assignmentData['acceptTime'][i]):
                        answerData = extract_answer_data(a)
                        if answerData.has_key(keyword):
                            allMyAnswers.append(answerData)
    for ID, count in IDs.iteritems():
        print(ID + ": " +str(IDs[ID]))
            
    return allMyAnswers

In [22]:
allMyLocations = []
get_location_on_date(allMyLocations)
    
len(allMyLocations)
# allMyLocations[0] 546

3VLL1PIENQMZWGYUDI0QMZCBJ0POZ1: 692

692

In [77]:
# for k in allMyAnswers[0]: 
#     print k, allMyAnswers[0][k]
# allMyAnswers[0].keys()
# len(allMyAnswers)
hit = 0
hit = 1
hit = 2
hit = 3
print(allMyLocations[hit]['trialVideo'])
df1 = pd.DataFrame(allMyLocations[hit]['locations'])
df1

table1

,0,1,2,3,4,5,6,7,8,9,...,58,59,60,61,62,63,64,65,66,67
0,bread_plate,197.244331,105.596580,0,charger,48.309669,13.025566,0,coffee,315.695991,...,105.369301,0,salad_knife,367.585213,97.769874,0,soup_spoon,304.005684,104.190330,0
1,bread_plate,191.221596,269.573845,0,charger,48.309669,13.025566,0,coffee,315.695991,...,105.369301,0,salad_knife,367.585213,97.769874,0,soup_spoon,304.005684,104.190330,0
2,bread_plate,191.221596,269.573845,0,charger,48.309669,13.025566,0,coffee,315.695991,...,105.369301,0,salad_knife,367.585213,97.769874,0,soup_spoon,304.005684,104.190330,0
3,bread_plate,191.221596,269.573845,0,charger,48.309669,13.025566,0,coffee,315.695991,...,105.369301,0,salad_knife,367.585213,97.769874,0,soup_spoon,304.005684,104.190330,0
4,bread_plate,191.221596,269.573845,0,charger,48.309669,13.025566,0,coffee,315.695991,...,105.369301,0,salad_knife,367.585213,97.769874,0,soup_spoon,304.005684,104.190330,0
5,bread_plate,191.221596,269.573845,0,charger,48.309669,13.011360,0,coffee,315.681831,...,266.335197,0,salad_knife,367.585213,97.755668,0,soup_spoon,304.005684,104.176124,0
6,bread_plate,191.221596,269.573845,0,charger,48.309669,13.011360,0,coffee,315.681831,...,266.335197,0,salad_knife,367.585213,97.755668,0,soup_spoon,304.005684,104.176124,0
7,bread_plate,191.221596,269.573845,0,charger,48.309669,13.011360,0,coffee,315.681831,...,266.335197,0,salad_knife,367.585213,97.755668,0,soup_spoon,304.005684,104.176124,0
8,bread_plate,191.221596,269.573845,0,charger,48.309669,13.011360,0,coffee,315.681831,...,266.335197,0,salad_knife,367.585213,97.755668,0,soup_spoon,304.985786,268.153404,0

In [23]:
import csv
import os
from tqdm import tqdm

table_size = 448
object_names = {
    'bread_plate':'Bread Plate BB',
    'charger':'Charger BB',
    'coffee':'Coffee Plate BB',
    'dinner_plate':'Dinner Plate BB',
    'napkin':'Napkin Cloth BB',
    'water_glass':'Water Glass BB',
    'wine_glass':'Wine Glass BB',
    'wine_glass_1':'Wine Glass BB (1)',
    'wine_glass_2':'Wine Glass BB (2)',
    'butter_knife':'Butter Knife BB',
    'dessert_fork':'Dessert Fork BB',
    'dessert_spoon':'Dessert Spoon BB',
    'dinner_fork':'Dinner Fork BB',
    'dinner_knife':'Dinner Knife BB',
    'salad_fork':'Salad Fork BB',
    'salad_knife':'Salad Knife BB',
    'soup_spoon':'Soup Spoon BB'
}

f = os.path.expanduser("image_data/"+'HIT_'+str(0)+'_dummy.csv')
with open(f, mode='w') as locations_file:
    locations_writer = csv.writer(locations_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    locations_writer.writerow("")

time = 0
time_max = 0
for hit in tqdm(range(len(allMyLocations))):
    name = "image_data/"+'HIT_'+str(hit+1)+'_'+ allMyLocations[hit]['configName'].encode("ascii").replace('table_configs_new/','').replace('.json','') + '_'
    
    # create instructions file
    answer = allMyLocations[hit]
    j_answer = {}
    j_answer["video_name"] = answer["videoName"].encode("ascii")
    j_answer["ins_name"] = answer["instructionName"].encode("ascii").replace("instructions/data_","").replace(".json","")
    duration = answer["duration"]
    j_answer["duration"] = float(duration[len(answer["duration"])-1] - duration[0])/1000
    time = time + j_answer["duration"]
    if time_max < j_answer["duration"]:
        time_max = j_answer["duration"]
    instructions = []
    for ins in answer["instructions"]:
        sentence = ins.encode("ascii")
        instructions.append(sentence)
    
    # prepare for making a collage out of the submission
    j_answer["instructions"] = instructions
    with open(name.replace("image_data/HIT_","image_data_collage/")+"ins.json", 'w') as outfile:  # name+"instructions.json"
        json.dump(j_answer, outfile, indent=4, sort_keys=False)
    
    # ----------------------------------------------------------
    # create csv output file, which will be input to script
    #    MakePicture.cs in 'Table Setting Project' in Unity
    # ----------------------------------------------------------
    
    # in order for the Unity script to generate the first image despite 
    #    there is no different between it and the original conriguration,
    #    we create an empty csv file and nam it 'HIT_**_config_***_0.csv'
    f = os.path.expanduser(name + str(0)+'.csv')
    with open(f, mode='w') as locations_file:
        locations_writer = csv.writer(locations_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        locations_writer.writerow("")
        
    # create the other csv files
    for i in range(len(allMyLocations[hit]['locations'])):
        f = os.path.expanduser(name + str(i+1)+'.csv')
        with open(f, mode='w') as locations_file:
            locations_writer = csv.writer(locations_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
            data = allMyLocations[hit]['locations'][i]
            all_objects = []
            for j in range(len(data)):
                cell = data[j]
                if isinstance(cell, unicode):
                    cell = cell.encode("ascii")
                cell_type = j % 4
                if cell_type == 0:
                    object_info = []
                    object_info.append(object_names[cell])
                elif cell_type == 1:
                    object_info.append(cell/table_size)
                elif cell_type == 2:
                    object_info.append(cell/table_size)
                    object_info.append(0)
                elif cell_type == 3:
                    if cell == '0':
                        cell = 0
                    object_info.append(cell)
                    object_info.append(0)
                    object_info.append(0)
                    locations_writer.writerow(object_info)

print("Average time (in seconds): ", time/len(allMyLocations))
print("Max time (in seconds): ", time_max)

100%|██████████| 692/692 [00:04<00:00, 143.20it/s]

('Average time(in seconds): ', 450.18993786127226)
('Max time(in seconds): ', 1189.453)